### ISSUE TITLE
[Feature] create loadTest model and parser

### ISSUE THREAD

**Issue by sung-jun98** [api-ghost/api-ghost#39]
# feature request

## TODO

- [x] Generate configuration files (parameters) and results necessary for load testing
- [x] Create a parser capable of serializing and deserializing the generated models to and from JSON
- [x] Write valid test code using the models and parser

## Describe Solution

- Describe the specific approach or expected implementation to solve the problem.

## Additional Info

- You can check the formats of the planned YAML and JSON files through the contents provided in the link below.
https://www.notion.so/1f0c3f80c687806ab51ceb59cf4f916d?pvs=4

- load test parameter file
```yaml
name: "AAA"
description: "BBB"

loadTest:
  timeoutMs: 300
  thinkTimeMs: 1000
  loadPattern: 
	- vus: 100
             duration: 60 
	- vus: 2000
	   duration: 100
        - vus: 500
           duration: 50  
			
scenarios:
	- scenario1.yaml
	- scenario2.yaml
```

- load test result file
```json
{
	"timeStamp" : "2025-04-23T14:15:00.000",
	"baseUrl" : "http://com.ssafy.org" 
  "results": 
	  {
	      "iterations" : { 
			      "rate" : 96.5,
			      "count" : 965
			  },
			  "http_reqs" : { 
				  "rate" : 96.9,
				  "count" : 969 
			  },
			  "http_req_duration" : { 
				  "avg" : 8000, 
				  "min" : 3200,
				  "med" : 7100,
				  "max" : 26400,
				  "p(90)" : 12500,
				  "p(95)" : 18300
			  },
			  "http_req_failed" : { 
				  "rate" : 0,
				  "passes" : 969,
				  "fails" : 0
				},
				"vus" : { 
					"value" : 100,
					"min" : 0,
					"max" : 100
				}
		},
		
		"endpoints" : [
				{
					 "endpoint" : "/api/payment-methods",
					 "results" : {
						 //  same content from `iterations` to `vus`
					 }
				}, 
				
				{
					"endpoint" : "/api/view-mypage",
					 "results" : {
						 //same content from `iterations` to `vus` 
					 }
				}
		],
}

```
